name: ruby
channels:
- conda-forge
- defaults
dependencies:
- ca-certificates=2018.1.18=0
- gmp=6.1.2=0
- ncurses=5.9=10
- openssl=1.0.2n=0
- readline=7.0=0
- ruby=2.4.2=2
- tk=8.6.7=0
- yaml=0.1.6=0
- zlib=1.2.11=0

